name: Build Docker Image and Save Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t student-performance:latest .

    - name: Save Docker image as tarball
      run: docker save student-performance:latest -o student-performance.tar

    - name: Upload Docker image artifact
      uses: actions/upload-artifact@v3
      with:
        name: docker-image
        path: student-performance.tar
