- name: Log in to Docker Hub
  uses: docker/login-action@v2
  with:
    username: ${{ secrets.DOCKERHUB_USERNAME }}
    password: ${{ secrets.DOCKERHUB_TOKEN }}

- name: Deploy to server via SSH
  uses: appleboy/ssh-action@v0.1.7
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      docker pull ${{ secrets.DOCKERHUB_USERNAME }}/student-performance:latest
      docker service update --image ${{ secrets.DOCKERHUB_USERNAME }}/student-performance:latest student-perf_web || \
      docker stack deploy -c /path/to/docker-compose.yml student-perf
